# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload2', '0003_auto_20170502_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='student_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
