# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload2', '0004_thesis_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
