# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('ratio', models.IntegerField()),
                ('num_of_lecture', models.IntegerField()),
                ('num_of_lab', models.IntegerField()),
                ('program_ID', models.CharField(choices=[('1', '\u0e20\u0e32\u0e04\u0e1b\u0e01\u0e15\u0e34'), ('2', 'TEP/TEPE'), ('3', 'AUTO')], default='1', max_length=120)),
                ('num_of_student', models.IntegerField()),
                ('ratio_of_score', models.IntegerField()),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
