# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='program_ID',
            field=models.CharField(choices=[('\u0e20\u0e32\u0e04\u0e1b\u0e01\u0e15\u0e34', '1'), ('TEP/TEPE', '2'), ('AUTO', '3')], default='1', max_length=120),
        ),
    ]
