# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_auto_20170215_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='program_ID',
            field=models.CharField(choices=[('\u0e20\u0e32\u0e04\u0e1b\u0e01\u0e15\u0e34', '\u0e20\u0e32\u0e04\u0e1b\u0e01\u0e15\u0e34'), ('TEP/TEPE', 'TEP/TEPE'), ('AUTO', 'AUTO')], default='1', max_length=120),
        ),
    ]
