# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0006_auto_20170315_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='subject_ID',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
