# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0009_auto_20170501_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
