# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0010_auto_20170502_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
