# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0011_auto_20170502_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
