# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0015_auto_20170601_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='program_ID',
            field=models.CharField(max_length=120),
        ),
    ]
