# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0016_auto_20170601_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
