# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload7', '0003_auto_20170502_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='person_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
