# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workload6', '0002_position_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
