# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload6', '0003_auto_20170502_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='time_end',
            field=models.DateTimeField(max_length=120),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_start',
            field=models.DateTimeField(max_length=120),
        ),
    ]
