# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload6', '0005_auto_20170508_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='time_end',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_start',
            field=models.CharField(max_length=120),
        ),
    ]
