# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload3', '0003_auto_20170502_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='degree2',
        ),
    ]
